import { Lato } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css'
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import Navbar from "@/components/Navbar";
import "@/themes/index.scss"
import Footer from "@/components/Footer";

const lato = Lato({
  weight: '400',
  subsets: ['latin'],
})


export const metadata = {
  title: "Suit-Now",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={[lato.className]}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
